sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.8.2

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build --enable-tests

script:
  - cabal new-test all --enable-tests

notifications:
  email: false
